version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  user_service:
    image: nadea39/user-management-service:1.0
    container_name: user_service_container
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/user_management
      - PORT=3000
    depends_on:
      - mongo
  
  db_userm_populator:
    image: nadea39/user-management-service:1.0
    container_name: db_populator_container
    environment:
      - MONGO_URI=mongodb://mongo:27017/user_management
    depends_on:
      - mongo
    command: ["node", "populate-db.js"]
    restart: "no"

  # --- Your town & character stack ---
  mongo-town:
    image: mongo:6
    container_name: mongo-town
    restart: always
    ports:
      - "27019:27017"   # ⚠️ changed from 27017 to avoid port clash with "mongo"
    volumes:
      - mongo-town-data:/data/db

  mongo-character:
    image: mongo:6
    container_name: mongo-character
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo-character-data:/data/db

  townservice:
    image: livia994/townservice:1.0
    container_name: townservice
    restart: always
    ports:
      - "4001:4001"
    env_file:
      - ./TownService.env
    depends_on:
      - mongo-town

  characterservice:
    image: livia994/characterservice:1.0
    container_name: characterservice
    restart: always
    ports:
      - "4002:4002"
    env_file:
      - ./CharacterService.env
    depends_on:
      - mongo-character

volumes:
  mongo_data:
  mongo-town-data:
  mongo-character-data:
