version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongo_container
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - game_network

  user_service:
    image: nadea39/user-management-service:1.4
    container_name: user_service_container
    environment:
      - MONGO_URI=${MONGO_URI_USER}
      - USE_MOCKS=true
      - PORT=3000 
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - game_network
    env_file:
      - .env

  game_service:
    image: nadea39/gameservice:v1.0.2
    container_name: gameservice_container
    environment:
      - MONGO_URI=${MONGO_URI_GAME}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
    ports:
      - "3005:3005"
    depends_on:
      - mongo
    networks:
      - game_network
  
  db_userm_populator:
    image: nadea39/user-management-service:1.0
    container_name: db_populator_container
    environment:
      - MONGO_URI=mongodb://mongo:27017/user_management
    depends_on:
      - mongo
    command: ["node", "src/populate-db.js"]
    restart: "no"

  db_game_populator:
  image: nadea39/gameservice:v1.0.2
  container_name: game_db_populator
  environment:
    - MONGO_URI=mongodb://mongo:27017/gameservice
  depends_on:
    - mongo
  command: ["node", "src/gameServicePopulator.js"]
  restart: "no"
  networks:
    - game-network

volumes:
  mongo_data:
